import {Fahkwang} from 'next/font/google'
import Header from "@/components/Header";
import "./globals.css";

const fahkwang = Fahkwang ({
  weight: ['400', '500'],
  subsets: ['latin'],
  display: 'swap'
})

export const metadata = {
  title: "influencie",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br" className={fahkwang.className}>
      <body>
        <Header/>
        {children}
      </body>
    </html>
  );
}
